# Generated by Django 2.0 on 2018-12-02 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('contenu', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=46)),
                ('contenu', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date commentaire')),
            ],
            options={
                'verbose_name': 'commentaire',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='commentaires',
            field=models.ManyToManyField(related_name='commentaires', to='blog.Commentaire'),
        ),
    ]
