# Generated by Django 2.0 on 2018-12-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='commentaires',
            field=models.ManyToManyField(blank=True, related_name='commentaires', to='blog.Commentaire'),
        ),
    ]
